### ISSUE TITLE
FUNCTION_INVOCATION_FAILED when you try to sync with registrar

### ISSUE THREAD

**Issue by weeebdev** [superhooman/crashed.nu#2]
The POST request to `https://crashed.nu/api/trpc/registrar.sync?batch=1` fails with 
```
A server error has occurred

FUNCTION_INVOCATION_FAILED
```

**Comment by superhooman** [comment]
Sorry, I didn't notice your issue. 
This problem occurred when the registrar was working very slowly, so the serverless function timeout was exceeded.
Currently, it works without issues.
